export const GET_ALL_RESTAURANT_REQUEST = 'GET_ALL_RESTAURANT_REQUEST';
export const GET_ALL_RESTAURANT_FAILURE = 'GET_ALL_RESTAURANT_FAILURE';
export const GET_ALL_RESTAURANT_SUCCESS = 'GET_ALL_RESTAURANT_SUCCESS';

export const GET__BOOKINGS_REQUEST = 'GET__BOOKINGS_REQUEST';
export const GET__BOOKINGS_FAILURE = 'GET__BOOKINGS_FAILURE';
export const GET__BOOKINGS_SUCCESS = 'GET__BOOKINGS_SUCCESS';

export const GET__TODAYS_BOOKING_REQUEST = 'GET__TODAYS_BOOKING_REQUEST';
export const GET__TODAYS_BOOKING_FAILURE = 'GET__TODAYS_BOOKING_FAILURE';
export const GET__TODAYS_BOOKING_SUCCESS = 'GET__TODAYS_BOOKING_SUCCESS';

export const GET__CANCELLED_BOOKING_REQUEST = 'GET__CANCELLED_BOOKING_REQUEST';
export const GET__CANCELLED_BOOKING_FAILURE = 'GET__CANCELLED_BOOKING_FAILURE';
export const GET__CANCELLED_BOOKING_SUCCESS = 'GET__CANCELLED_BOOKING_SUCCESS';

export const GET__ALL_CATEGORIES_REQUEST = 'GET__ALL_CATEGORIES_REQUEST';
export const GET__ALL_CATEGORIES_FAILURE = 'GET__ALL_CATEGORIES_FAILURE';
export const GET__ALL_CATEGORIES_SUCCESS = 'GET__ALL_CATEGORIES_SUCCESS';

export const GET_ALL_SEATS_BY_RESTAURANT_REQUEST =
  'GET_ALL_SEATS_BY_RESTAURANT_REQUEST';
export const GET_ALL_SEATS_BY_RESTAURANT_FAILURE =
  'GET_ALL_SEATS_BY_RESTAURANT_FAILURE';
export const GET_ALL_SEATS_BY_RESTAURANT_SUCCESS =
  'GET_ALL_SEATS_BY_RESTAURANT_SUCCESS';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
